### ISSUE TITLE
Feature : Could not connect to schema views in postgres

### ISSUE THREAD

**Issue by rasheedk** [ananas-analytics/ananas-desktop#101] opened 2019-08-05 09:02 UTC
Please add a feature for adding datasource from postgres views of a database

**Comment by bhou** [comment] 2019-08-05 20:19
It should work if you put your view name as the table name settings, and update the SQL with the corresponding view name.
![Screenshot from 2019-08-05 22-15-01](https://user-images.githubusercontent.com/2302370/62492504-0f0af380-b7cf-11e9-93a5-ed81ffb7a28e.png)

**Comment by rasheedk** [comment] 2019-08-07 06:23
Please see this

![image](https://user-images.githubusercontent.com/25896360/62599381-affdc980-b909-11e9-8351-bcddaf0354d1.png)

I am not able to access the data.
If i execute the view in query executor of pgadmin, its returning data.

**Comment by millboh** [comment] 2019-08-07 18:54
The view schema autodetection seems not to be working for any columns of your view. It does not matter if the view is public or private. The issue is that the column types are supported. 

@rasheedk It would help if you could describe the SQL types of each column in your view . ( \d schema_name.viewname or using PgAdmin III)

**Comment by rasheedk** [comment] 2019-08-19 09:32
My column data type contains xml , big int and date .
can you please clarify weather xml data type is supported or not ?

**Comment by bhou** [comment] 2019-08-20 05:19
@rasheedk I can reproduce the issue with XML type column in version 0.8.2. The great news is, it has been fixed in 0.9.0, which will be released in this week. 

![xml type](https://user-images.githubusercontent.com/2302370/63319495-9b163280-c31a-11e9-95fb-0d42fdb2250a.png)

**Comment by bhou** [comment] 2019-08-25 23:56
Fixed in 0.9.0

**Closed by bhou** 2019-08-25 23:56 UTC
Labels: bug
